---
- name: Update web servers
  hosts: nginx
  become: yes

  tasks:
  - name: update and install nginx
    apt:
      name: nginx
      state: present
      update-cache: true
    # when: ansible_distribution == "Ubuntu"

  - name:  remove nginx default sites
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: adding nginx config
    copy:
      src: load.conf
      dest: /etc/nginx/conf.d/load.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes  

  - name: Restarting nginx with load balancing config
    service:
      name: nginx
      state: reload